### ISSUE TITLE
v2 umbrella

### ISSUE THREAD

**Issue by edorivai** [ReactTraining/react-media#110]
# 2.0
- [x] change `query` prop to `queries` (#72)
- [ ] two-pass render + migrate to `componentDidMount` (solves #81, #91, #109, PR: #96)
- [ ] run tests in `<Strict>` mode

# 2.1
- [ ] implement a hooks API, exposed as `react-media/hooks`

**Comment by tstirrat15** [comment]
Want help with any of this?

**Comment by edorivai** [comment]
@tstirrat15 Feel free to take a stab at any the last three - Strict mode tests, docs, hooks. I'm a bit short on time, but let me know if you want to start on one, and I'll write up some thoughts I have on that particular item.

**Comment by tstirrat15** [comment]
Strict mode tests sounds the most immediately tractable. Is that pretty straightforward?

**Comment by edorivai** [comment]
Yes it should be. The idea would be to wrap all tests in `<React.StrictMode>`. @mjackson mentioned they're [already doing this](https://github.com/ReactTraining/react-router/blob/0853628daff26a809e5384f352fada57753fc1c3/packages/react-router/modules/__tests__/utils/renderStrict.js) in react-router. Instead of calling `ReactDOM.render` directly, they pass their components under test to a `renderStrict` function they defined, which wraps it in `StrictMode`.

I don't see any actual assertions around Strict mode, but I guess it would be easily verifiable in the Travis runs as soon as something is violating strict mode.

Does that all make sense?

**Comment by tstirrat15** [comment]
Yep.

What I've seen in using it in our own project is that it throws warnings at runtime. Is Travis configured to treat warnings as failures? Otherwise it'd probably entail manual review of the test output.

**Comment by edorivai** [comment]
Yeah I think manual review is fine. I usually run the tests before publishing, but more importantly, when users start complaining that something is not compliant with strict mode, we would be able to verify it quickly by running the tests.

**Comment by tstirrat15** [comment]
Do you want/need any help with the docs? Did you have an idea for a direction on that?

**Comment by South-Paw** [comment]
Would it possible to get an RC build released on npm for the `next` branch?

I'd really like to see if the 2 pass renderer solves some issues I'm seeing in a project.

**Comment by edorivai** [comment]
@South-Paw Yeah, that would be possible. Only gotcha is that the next branch has a big breaking change, we replaced the `query` prop for `queries`. See #119 and #69 for details.

Would it still be useful for you to test out the `next` branch, given this breaking change?

**Comment by South-Paw** [comment]
Yeap I think it'd be fine to test it out even with those changes.

It won't be to hard to go through and migrate `query` to `queries` - from what I can see I can still put a string into `queries` and the render pattern remains as `{matches => matches ? <div>a</div> : <div>b</div> }` right?

**Comment by edorivai** [comment]
@South-Paw No, the `queries` prop has to be an object, where each of it's keys represents a media query:

```jsx
<Media queries={{
    sm: "(max-width: 1000px)",
    lg: "(max-width: 2000px)"
  }}>
  {(matches) =>
    <>
      { matches.sm && <span>I'm small</span>}
      { matches.lg && <span>I'm large</span>}
    </>
  }
</Media>
```

**Comment by edorivai** [comment]
@South-Paw Hey I just prepared everything for an alpha release, but sadly the deploy process halted due to an invalid npm token. I don't have access to the npm project, so we'll have to wait for @mjackson to fix the token in Travis. See #120 for details.

**Comment by South-Paw** [comment]
Hi, its been 2 weeks and @mjackson hasn't responded to #120 - has there been any movement on this?

Still pretty keen to try test this 👍

**Comment by edorivai** [comment]
Hey guys, I'm really sorry about the delay. I've dm'd @mjackson, but I imagine his inboxes must be bursting :sweat_smile:.

In the meantime, would it be an option for you guys to test the `next` branch locally? You can check out a fork of this repo, then:
- check out the `next` branch
- run `npm run build`
- run `npm link`
- inside your own project: `npm link react-media`

Now run your project as usual, it should use your local copy of `react-media`.

**Comment by baumzeit** [comment]
Thank you!
I will try that later today. 
Awesome work :)

**Comment by baumzeit** [comment]
During build I get the following error:
I thought I posted this in case it's relevant for the upcoming release.
I dug into the error a bit but this is not something I can solve as of yet..

`modules/index.js → esm/react-media.js...
[!] (size-snapshot plugin) Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Media.js' in '/'
Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Media.js' in '/'
    at compiler.run (C:\_code\projects\react-media\node_modules\rollup-plugin-size-snapshot\dist\treeshakeWithWebpack.js:58:16) [.. further traceback]
`

**Comment by edorivai** [comment]
@baumzeit Huh did the following, and was able to successfully build the project:

- Checkout latest version of the `next` branch
- Run `npm ci` to install dependencies
- Run `npm run build`

Did you do something similar?

**Comment by baumzeit** [comment]
Yes, I can confirm:

- forked react-media
- cloned the repo
- npm install (also tried ci)
-npm run build

yields the above error.

Here is the complete trace:

`modules/index.js → esm/react-media.js...
[!] (size-snapshot plugin) Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Media.js' in '/'
Error: ModuleNotFoundError: Module not found: Error: Can't resolve './Media.js' in '/'
    at compiler.run (C:\_code\projects\react-media\node_modules\rollup-plugin-size-snapshot\dist\treeshakeWithWebpack.js:58:16)
    at finalCallback (C:\_code\projects\react-media\node_modules\webpack\lib\Compiler.js:210:39)
    at hooks.done.callAsync.err (C:\_code\projects\react-media\node_modules\webpack\lib\Compiler.js:226:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\_code\projects\react-media\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\_code\projects\react-media\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\_code\projects\react-media\node_modules\webpack\lib\Compiler.js:224:21)
    at hooks.afterCompile.callAsync.err (C:\_code\projects\react-media\node_modules\webpack\lib\Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\_code\projects\react-media\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\_code\projects\react-media\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\_code\projects\react-media\node_modules\webpack\lib\Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\_code\projects\react-media\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\_code\projects\react-media\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (C:\_code\projects\react-media\node_modules\webpack\lib\Compilation.js:1323:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\_code\projects\react-media\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\_code\projects\react-media\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (C:\_code\projects\react-media\node_modules\webpack\lib\Compilation.js:1314:32) [... npm error messages]`

**Comment by edorivai** [comment]
@baumzeit Damn, you think this could be a windows issue? I don't have a windows environment at hand to test :\

In any case, when the build get's fixed you should be able to test the alpha release. Sorry again for the wait

**Comment by baumzeit** [comment]
@edorivai It looks like it's a windows issue.
I tested it out on another windows machine with the same result.
- checkout `next`
- `npm ci`
- `npm run build`

**Comment by South-Paw** [comment]
I've gotten really frustrated waiting for a month so when I need to test and/or fix the SSR issue a few websites now.

So I'm going through building and publishing my own version of `react-media` and hit the same issue as @baumzeit on Windows.

Problem seems to be in the `rollup-plugin-size-snapshot` package. Updating it to v0.8.0 changed the error to

```
[!] (size-snapshot plugin) TypeError: Cannot read property 'find' of undefined
TypeError: Cannot read property 'find' of undefined
    at then.then (E:\dev\Github\react-media\node_modules\rollup-plugin-size-snapshot\dist\treeshakeWithRollup.js:67:36)
```

Can't tell if its required or not, but removing the plugin from the `rollup.config.js` allows the package to build again.

I'll be publishing the `next` branch here if anyone else wishes to use it: https://www.npmjs.com/package/@south-paw/react-media

**Comment by South-Paw** [comment]
Scratch that, doesn't seem my republished version works either.

```
 ERROR  Failed to compile with 1 errors

This relative module was not found:

* ./Media.js in ./node_modules/@south-paw/react-media/esm/react-media.js
× ｢wdm｣:
ERROR in ./node_modules/@south-paw/react-media/esm/react-media.js
Module not found: Error: Can't resolve './Media.js' in 'E:\dev\Github\...\node_modules\@south-paw\react-media\esm'
 @ ./node_modules/@south-paw/react-media/esm/react-media.js 1:0-34 2:0-37 2:0-37
 @ ./src/templates/Site.js
 @ ./src/pages/acceptable-use-policy.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://dev//Github//...//.cache//app
i ｢wdm｣: Failed to compile.
```

Gonna go find another package to do media queries now 👋

**Comment by South-Paw** [comment]
Scratch that, doesn't seem my republished version works either.

```
 ERROR  Failed to compile with 1 errors

This relative module was not found:

* ./Media.js in ./node_modules/@south-paw/react-media/esm/react-media.js
× ｢wdm｣:
ERROR in ./node_modules/@south-paw/react-media/esm/react-media.js
Module not found: Error: Can't resolve './Media.js' in 'E:\dev\Github\...\node_modules\@south-paw\react-media\esm'
 @ ./node_modules/@south-paw/react-media/esm/react-media.js 1:0-34 2:0-37 2:0-37
 @ ./src/templates/Site.js
 @ ./src/pages/acceptable-use-policy.js
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi event-source-polyfill (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false E://dev//Github//...//.cache//app
i ｢wdm｣: Failed to compile.
```

How long until the npm token gets fixed @edorivai? I've pinged @mjackson twice on twitter and I doubt he's seen either... but its getting really frustrating that it's been a month and a half with no movement on the issue.

**Comment by edorivai** [comment]
@South-Paw Hey man, I understand that you're frustrated. I've pinged @mjackson on twitter, as well as email, so there isn't too much I can do anymore. I've also considered publishing under a different npm package, but honestly didn't get the time to do so yet.

One quick remark on the error you're running into. When I build on my system (I'm running Linux), there's only a single file inside the `esm` directory (see screenshot below). Reading your error message, it seems to me that the `esm/react-media.js` file is trying to import the `./Media.js` file, which is weird, since that file should be rolled up into `react-media.js`. Could you maybe tell me what the files inside your `esm` directory look like?

![image](https://user-images.githubusercontent.com/765358/54091804-b3098380-4384-11e9-9d36-6072d5184d88.png)

**Comment by South-Paw** [comment]
@edorivai Sorry, I know its not your fault and @mjackson is obviously a busy person as well - just annoying to have a ~70k dl/w package, that works really really well and has a good 2.0 update coming to be hamstrung by a such a trivial issue 😥

I've been out tonight so no code time, but I'll run another build tomorrow and take a screenshot. Thanks for the continued replies 👍

**Comment by moflo** [comment]
Hi @edorivai - we needed a hooks port so we created one, here: [react-media-hooks](https://github.com/moflo/react-media-hooks). I don't plan to publish to npm as this would likely be in conflict with your 2.0 plans. Also, we would need to add more tests, TS support, etc., but this private version works for us. Thanks!

**Comment by edorivai** [comment]
@moflo Thanks :smile:. We're planning to add hooks as well, but we first want to get v2 published.

@South-Paw @baumzeit Good news, the deployment problems have been fixed :tada:. You should be able to install `react-media@next`. Let me know how it goes!

**Comment by South-Paw** [comment]
@edorivai awesome, thanks 👍

**Comment by South-Paw** [comment]
@edorivai gave `react-media@next` a run on the Gatsby website I needed it on - unfortunately the 2 pass renderer that I thought would solve the issue that I'm seeing didn't make a difference when I built the site for deployment 😞

While I don't think I've got a specific Gatsby issue, I do think its to do with how Gatsby statically creates the website for build/publish and how it interacts with `react-media` or possibly `styled-components` inside of `react-media`

Unsure what steps I can take next on this 🤔 so any suggestions are welcome

**Comment by edorivai** [comment]
@South-Paw If you have the time, it would be incredibly helpful if you could post a minimal reproduction repository that I can try out for myself.

One thing I can add though, I took a look with @baumzeit at the problems he was having, and he was using react-static. This was before the two-pass render was published to npm, so we quickly implemented the two-pass render in his own codebase. And that did seem to solve his problem (inconsistent DOM after rehydration).

**Comment by edorivai** [comment]
@baumzeit If you have time, would you be so kind to test `react-media@next` in your project, and remove the custom fix for your two-pass rendering issue?

**Comment by tstirrat15** [comment]
Does that mean that `queries` is available in `@next` and that we should go ahead and give it a go?

**Comment by edorivai** [comment]
It does, so yes, please try it out😊

**Comment by joefiorini** [comment]
@edorivai I had to write a component that could listen on multiple, device-specific media queries, so I went ahead and used this alpha. It's working great in our uses of a single query and our new use of multiple queries. The one downside is that now the typescript defs are out-of-date. I tried my hardest to write a type that would tie the keys from the `queries` prop to the keys in the `match` prop, but couldn't figure it out in a way that would work with a union (or conditional type) to also allow a single `query` prop. If I can figure it out I'll open a PR, but need to move on for now.

**Comment by edorivai** [comment]
@joefiorini Thanks for letting me know! I'll have to take a look at the TS definitions

**Comment by deasems** [comment]
What's the status 2.0 and hooks support?

**Comment by tstirrat15** [comment]
I can put through a PR for the hook update.

**Comment by abenhamdine** [comment]
For any one interested : hooks are available in 2.X branch, with `npm install react-media@next`
It's a RC version but it works perfectly for us.

Big thx to @tstirrat15 and @edorivai for this !

**Comment by JonasJuss** [comment]
I just tested react-media@next with my gatsby website and I can confirm that the two-pass rendering does not seem to work anymore.

I had to revert back to the 1.10.0 to make everything work as intended again.

**Comment by tstirrat15** [comment]
@JonasJuss can you give me an example of how it's supposed to work and how it fails? I'll admit that I don't understand two-pass rendering well enough, and it hasn't yet been captured in a test. I'd like to write one.
